#!/bin/sh
# devtmpfs does not get automounted for initramfs
set -x
/bin/mount -t devtmpfs devtmpfs -o mode=0755 /dev
mkdir -p /dev/pts
chmod 755 /dev/pts
/bin/mount -t devpts devpts /dev/pts
ln -s /dev/pts/ptmx /dev/ptmx
/bin/mount -t sysfs sysfs /sys
/bin/mount -t proc none /proc
echo "Good morning!"
#mknod -m 622 /dev/console c 5 1
#mknod -m 666 /dev/null c 1 3
#mknod -m 666 /dev/zero c 1 5
#mknod -m 666 /dev/ptmx c 5 2
#mknod -m 666 /dev/tty c 5 0
#mknod -m 444 /dev/random c 1 8
#mknod -m 444 /dev/urandom c 1 9
#chown root:tty /dev/console
#chown root:tty /dev/ptmx
#chown root:tty /dev/tty

exec 0</dev/console
exec 1>/dev/console
exec 2>/dev/console
#exec /sbin/init $*
export ROOT="/dev/mmcblk1p9"
mkdir /mnt/root


#mkdir -p /data
#/bin/mount /dev/block/mmcblk0p12 /data
#mkdir -p /data/local
#find /dev/ > /data/local/dev.txt

#sleep 5

#find /dev ! -name "tty*"
#find /dev ! -wholename "*tty*" ! -wholename "*char*" ! -wholename "*char*" ! -wholename "*bus*" ! -wholename "*disk*" ! -wholename "*loop*" ! -wholename "*block*"
#stat /dev/ptmx || true

#find /dev -name ptmx

#echo "This is an ugly hack to prevent glitches"
#c=0
#while true
#do
##head -c30 </dev/urandom|xxd -p -u
#if [ $c -ge 100 ] ; then break; fi
#c=$(($c + 1))
#usleep 40000 # sleep 50ms
#done
#sleep 5

echo "Hi there!"

modprobe g_ffs idVendor=0x18d1 idProduct=0x4e42 iSerialNumber="buildroot"

#echo $(ls /sys/class)
mkdir -p /dev/usb-ffs/adb
mount -t functionfs adb /dev/usb-ffs/adb -o uid=2000,gid=2000

#strace -s 32 $(which adbd)
adbd &

#while true
#do
#echo "sleep..."
#sleep 5
#done
#/bin/mount $ROOT /mnt/root
#/bin/mount -t sysfs none /mnt/root/sys
#/bin/mount -t proc none /mnt/root/proc
#/bin/mount -t devtmpfs none /mnt/root/dev
#/bin/mount -t tmpfs none /mnt/root/tmp
#echo mounted $ROOT on /mnt/root
#/bin/mount
#echo "Launching switch_root..."
#exec /sbin/switch_root /mnt/root /sbin/init

