#!/bin/sh
# devtmpfs does not get automounted for initramfs
#set -x
/bin/mount -t devtmpfs devtmpfs -o mode=0755 /dev
mkdir -p /dev/pts
chmod 755 /dev/pts
/bin/mount -t devpts devpts /dev/pts
ln -s /dev/pts/ptmx /dev/ptmx
/bin/mount -t sysfs sysfs /sys
/bin/mount -t proc none /proc
echo "Good morning!"

exec 0</dev/console
exec 1>/dev/console
exec 2>/dev/console
#exec /sbin/init $*

echo "Hi there!"

modprobe g_ffs idVendor=0x18d1 idProduct=0x4e42 iSerialNumber="buildroot"

#echo $(ls /sys/class)
mkdir -p /dev/usb-ffs/adb
mount -t functionfs adb /dev/usb-ffs/adb -o uid=2000,gid=2000

# can't start adbd here because we call switch_root later
#adbd &

# to hopefully prevent display glitches
#{
#  while true
#  do
#    cat /etc/movglobe.vt | pv -q -L 9600 || true
#  done
#} &

#cat /etc/movglobe.vt | pv -q -L 9600 || true

sleep 5
mkdir -p /ext

export ROOT="/ext/ubuntu.img"
mkdir /mnt/root

/bin/mount /dev/mmcblk0p1 /ext
/bin/mount $ROOT -o loop,rw /mnt/root
/bin/mount -t sysfs none /mnt/root/sys
/bin/mount -t proc none /mnt/root/proc
/bin/mount -t devtmpfs none /mnt/root/dev
/bin/mount -t tmpfs none /mnt/root/tmp
echo mounted $ROOT on /mnt/root
/bin/mount
echo "Launching switch_root..."
exec /sbin/switch_root /mnt/root /sbin/init || while true; do sleep 5; done
